### ISSUE TITLE
Save machine

### ISSUE THREAD

**Issue by proatgram** [jeffpar/pcjs#6] opened 2020-11-08 02:22 UTC
I do not know if this is a current issue or not, but I am having a bit of trouble saving a machine and getting a state.json file. I found a blog post on the pcjs.org webpage https://www.pcjs.org/blog/2016/02/17/ that said I should get a file that contained a big chunk of Javascript code containing things like the state, machine.xml, ext. but when I click on it and input the file into <script src="pcx86.js"></script> and open the html file, the place where the screen would show up displays nothing but black. It might just be me and I do not yet understand how to use the save machine function but if someone could help me that would be great! Thanks!

**Comment by jeffpar** [comment] 2020-11-10 21:39
Duplicate of issue #4 -- should be resolved now.

**Closed as completed by jeffpar** 2020-11-10 21:39 UTC

**Comment by IAW9927** [comment] 2021-03-09 14:24
When I tried a save even PCjs v2.07 will not let me get the machine locally working. So, can you give me a archive and then I try the main thing for the machine? Thanks.
